# RUFF CONFIG
[tool.ruff]  # RUFF CONFIG:
line-length = 120

[tool.ruff.lint]
ignore = [
    "E722",  # try-except without exception
]

# PYLINT CONFIG
[tool.pylint."MESSAGES CONTROL"]  # PYLINT CONFIG:
disable = [
    "C0103",  # Constant name doesn't conform to UPPER_CASE naming style
    "W0603",  # Using the global statement
    "W0511",  # TODO
    "C0114",  # Missing module docstring
    "R0903",  # Too few public methods
    "R0917",  # too-many-positional-arguments
    "W1203",  # logging-fstring-interpolation
]

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.BASIC]
max-args = 8
max-attributes = 15
good-names = ["i", "j", "k", "_"]
bad-names = ["foo", "bar", "baz", "bebra", "lebra", "aboba"]

[tool.pylint.MISCELLANEOUS]
notes = ["FIXME", "XXX", "TODO"]

[tool.pylint.SIMILARITIES]
min-similarity-lines = 4
ignore-comments = true
ignore-docstrings = true
ignore-imports = false

# FLAKE 8 CONFIG:
[tool.flake8]
exclude = [
    ".git",
    "pycache",
    "venv",
    "__init__.py",
]
max-line-length = 120
ignore = [
    "E722",  # Do not use bare except
    "W503"  # Line break before binary operator
]

# MYPY CONFIG:
[tool.mypy]
python_version = "3.10"
strict = true

[[tool.mypy.overrides]]
module = [
]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["."]
